// Copyright (c) 2010 Dell Inc.  All rights reserved.
// ==================================================================
// DCIM_ControllerBatteryView
// ==================================================================

      [Description(
           "DCIM_ControllerBatteryView is a derivation of DCIM_View "
           "with controller specific data.") ]
class DCIM_ControllerBatteryView : DCIM_View {

      [Key, Description (
          "A string containing the Fully Qualified Device Description "
          "A user-friendly name for the object. This property allows each "
          "instance to define a user-friendly name in addition to its key "
          "properties, identity data, and description information. "
          )]
  string InstanceID;

      [Description (
          "A string containing the Fully Qualified Device Description "
          "A user-friendly name for the object. This property allows each "
          " instance to define a user-friendly name in addition to its key "
          " properties, identity data, and description information. "
          )]
  string FQDD;

      [Description (
          "A string containing the friendly Fully Qualified Device Description "
          "A property that describes the device and its location"
          )]
  string DeviceDescription;   

      [Description (
          "PrimaryStatus provides a high level status value, intended to "
          "align with Red-Yellow-Green type representation of status. "
          "It should be used to "
          "provide high level and detailed health status of the "
          "controller and its subcomponents. PrimaryStatus consists "
          "of one of the following values: Unknown, OK, Degraded or Error. "
          "\"Unknown\" indicates the implementation is in general capable "
          "of returning this property, but is unable to do so at this time. "
          "\"OK\" indicates the controller is functioning normally. "
          "\"Degraded\" indicates the controller is functioning below "
          "normal. \"Error\" indicates the controller is in an Error "
          " condition. " ),
       ValueMap { "0", "1", "2", "3", "0x8000", "0xFFFF" },
       Values { "Unknown", "OK", "Degraded", "Error", "DMTF Reserved", "Vendor Reserved"}]
  uint32 PrimaryStatus;

      [Description (
          "RAIDState provides the current battery status. The state "
          "can have one of the following values."),
       ValueMap { "0", "1", "6", "7", "9", "10", "12" },
       Values { "Unknown", "Ready", "Failed", "Degraded", "Missing", "Charging", "Below Threshold"}]
  uint16 RAIDState;

};
